### ISSUE TITLE
PHPRETS issue: Message "Server Temporarily Disabled"

### ISSUE THREAD

**Issue by r-interactive** [troydavisson/PHRETS#102]
The updating was working normally, but I am receiving this message when I run this  job.

```
Array
(
    [type] => rets
    [code] => 20050
    [text] => Server Temporarily Disabled. The client must issue a Login request first after the server is available. Reference ID:fa04c6c6-9983-4e6a-ad58-07cafa409122
)
```

What do this mean?

**Comment by menriquez** [comment]
either the RETS server you are accessing is temporarily down due to some
issue or the creds you are logging with have been suspended (usually
because the agent didnt pay their dues or something)

hope this helps.

On Mon, Apr 4, 2016 at 8:38 AM, r-interactive <notifications@github.com>
wrote:

> The updating was working normally, but I am receiving this message when I
> run this job.
>
> Array
> (
>     [type] => rets
>     [code] => 20050
>     [text] => Server Temporarily Disabled. The client must issue a Login request first after the server is available. Reference ID:fa04c6c6-9983-4e6a-ad58-07cafa409122
> )
>
> What do this mean?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/troydavisson/PHRETS/issues/102>
>



-- 

Mark Enriquez, Owner/Lead Developer
321.328.7301

**Comment by r-interactive** [comment]
Hi @menriquez,

Thank you for your prompt reply.
