### ISSUE TITLE
I can't get Photos of results

### ISSUE THREAD

**Issue by daviddela11** [troydavisson/PHRETS#166]
Hi,
I have a problem to get Photo Objects.
I get all data of the Search request.
However when I make the GetObject request with all_ids:
     $all_ids = $results->lists('ListingID');
     $photos = $rets->GetObject('Property', 'Photo', $all_ids);
The answer is "Unknown Resource (identifier) Reference ID"

I tried to get sysid instead of ListingID but I couldn't get it.
How could I get the Photo objects?

I'm using PHRETS 2.4. 

Thanks

**Comment by daviddela11** [comment]
Finally I solved it. 
$all_ids must be the list of sysid. How I said before, I couldn't get that values. The reason: because I got them with StandardNames = 1 and sysid doesnt have defined a standard name.
The solution: I changed the search call using de ids instead of the StandardNames of the metadata.

**Comment by 1014825794** [comment]
Hello, I have the same problem as you, how did you get IDS? Can you tell me, maybe we can communicate with each other in the future！！！
Here's my question





   We have a problem that can not be solved, so we ask you for help 。

   First of all, we have MLS accounts that you got from them. They are:

      $rets_login_url = "https://pt.rets.crmls.org/contact/rets/login";
        $rets_username = "**FANG";
        $rets_password = '**!y$jTv'; 

   I can make sure this account is available，I can make sure this account is available, because I can get the data through this account(That is the basic information Housing)，

   I got the data through this phprets 1.x and put it in the CSV, which is what we need。

   I see your document is using this method: GetObject ("property", "photo", "*", "1") ,to get the picture.

   There are a lot of mlsid fields involved in CSV, but I don't know which field to associate to get the corresponding picture.

   So please help me, thank you very much!!!





------------------ 原始邮件 ------------------
发件人: "daviddela11";<notifications@github.com>;
发送时间: 2017年8月29日(星期二) 晚上6:59
收件人: "troydavisson/PHRETS"<PHRETS@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [troydavisson/PHRETS] I can't get Photos of results (#166)




Hi,
 I have a problem to get Photo Objects.
 I get all data of the Search request.
 However when I make the GetObject request with all_ids:
 $all_ids = $results->lists('ListingID');
 $photos = $rets->GetObject('Property', 'Photo', $all_ids);
 The answer is "Unknown Resource (identifier) Reference ID"
 
I tried to get sysid instead of ListingID but I couldn't get it.
 How could I get the Photo objects?
 
Thanks
