### ISSUE TITLE
[1.x] Forces php to return exit status of 0 on error

### ISSUE THREAD

**Issue by etherealite** [troydavisson/PHRETS#168]
The call to die in this [location ](https://github.com/troydavisson/PHRETS/blob/1.x/phrets.php#L483)causes my entire program to exit without mercy. I want to handle this error not have my script die.

```php
		if (empty($this->capability_url['Search'])) {
			die("SearchQuery() called but unable to find Search location.  Failed login?\n");
		}
```

EDIT:

I realize I'm supposed to ensure that  `::Connect()` populates `::$capability_url` with the required keys before I call `::searchQuery`.  Being required to understand the semantics of how the PHRETS class works at such a close level just to keep it from calling `die(0)` on me is... interesting. 

Calling  exit 0 means nothing went wrong,  that's not the case here. Can we at least exit with a non zero?

**Comment by rewkyle** [comment]
I'm out of the office from Friday September 1'st, and will be returning on September 11th. 
 
If you have any urgent feed related issues, please contact Support at 
support@realestatewebmasters.com  

Otherwise I will respond on my return. 
 
Cheers! 
-- 
Kyle Misner 
Technical Support Specialist
Real Estate Webmasters 
kyle@realestatewebmasters.com

**Comment by 1014825794** [comment]
Hey sir.

   We have a problem that can not be solved, so we ask you for help 。

   First of all, we have MLS accounts that you got from them. They are:

      $rets_login_url = "https://pt.rets.crmls.org/contact/rets/login";
        $rets_username = "**FANG";
        $rets_password = '**!y$jTv'; 

   I can make sure this account is available，I can make sure this account is available, because I can get the data through this account(That is the basic information Housing)，

   I got the data through this phprets 1.x and put it in the CSV, which is what we need。

   I see your document is using this method: GetObject ("property", "photo", "*", "1") ,to get the picture.

   There are a lot of mlsid fields involved in CSV, but I don't know which field to associate to get the corresponding picture.

   So please help me, thank you very much!!!




         Good nice to you!!!



------------------ 原始邮件 ------------------
发件人: "REW Kyle Misner";<notifications@github.com>;
发送时间: 2017年9月2日(星期六) 中午11:17
收件人: "troydavisson/PHRETS"<PHRETS@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [troydavisson/PHRETS] [1.x] Forces php to return exit status of 0on error like conditions (#168)



I'm out of the office from Friday September 1'st, and will be returning on September 11th. 
  
 If you have any urgent feed related issues, please contact Support at 
 support@realestatewebmasters.com  
 
 Otherwise I will respond on my return. 
  
 Cheers! 
 -- 
 Kyle Misner 
 Technical Support Specialist
 Real Estate Webmasters 
 kyle@realestatewebmasters.com

**Comment by troydavisson** [comment]
I don't disagree with the `die` approach being a bad design decision on my part many years ago.  That said, I have no plans of making updates to the 1.x version and version 2 doesn't have this behavior, so I'd recommend looking at an update to 2.x or modifying a copy of PHRETS 1.x for your local use.

As far as the issue of knowing some fundamental pieces of PHRETS in order to use it, some things are unavoidable.  In order for PHRETS to operate in a user-friendly way, it provides methods to make various calls to the various endpoints supported by most RETS servers.  However, if a server doesn't support a certain endpoint (transaction, or "capability" as the RETS spec calls it) or your account doesn't have access to an endpoint, the server may choose to not advertise that ability.  In those instances, PHRETS cannot satisfy a particular method call because the server doesn't support it's end of the deal, and so an error is the only reasonable choice in my mind.

**Comment by etherealite** [comment]
Ok, all is well since I'm doing the checks I need to ensure die() is never called.

Thanks.
