### ISSUE TITLE
PHRETS 1.72 Question

### ISSUE THREAD

**Issue by ntmk** [troydavisson/PHRETS#318]
@troydavisson Up until this week this version was running fine I have checked the 1.x branch and nothing has changed. when run now the code currently fails at SearchQuery() called but unable to find Search location. I cannot see the reason why. Could you give some insite? Again the only thing that has been changed since the first use was credential and pull back.

**Comment by ntmk** [comment]
Move to google group

**Comment by troydavisson** [comment]
That indicates an issue with the credentials and the ability for your code to successfully log into the remote system.  Once it can successfully log in, the code will know where to make follow-up Search requests, and the error indicates that it doesn't know where to make those requests (because the login failed).
