### ISSUE TITLE
Unable to Connect To RETS

### ISSUE THREAD

**Issue by Aeyzaz** [troydavisson/PHRETS#46]
FireWall Test:
Firewall Test: google.com:80 GOOD
Firewall Test: demo.crt.realtors.org:80 FAILED
Firewall Test: demo.crt.realtors.org:6103 FAILED
Firewall Test: retsgw.flexmls.com:80 GOOD
Firewall Test: retsgw.flexmls.com:6103 GOOD
Firewall Result: At least one port 6103 test passed. Likely cause: One of the test servers might be down but connections on port 80 and port 6103 should work.

**Comment by premiumBH** [comment]
Hi There, Having the Exact issue! Hope someone has a solution to this by now? 
Perhaps if may be worth mentioning here that the MLS solution is my own and the solution was acquired from a company that has stopped support for the solution even before we went operational with our service. Now we're stuck with it and have live with it yet we're unable to use it to its fullest. It seems successful testing is essential to proceed with the integration and because the test fails as this 1st step we can't proceed. Wondering if changing (by customizing the test function) the crt.realtor.org test to our own server will be a viable fix? P.S. Please not we're setting up the service in NON-US country hence we dont really need to have other mls or realtor.org working with our solution. 

Thank you in advance.

**Comment by troydavisson** [comment]
@premiumBH which exact issue are you having?  There have been at least 2 different issues brought up here.

**Comment by premiumBH** [comment]
Firewall Test: google.com:80 GOOD
Firewall Test: demo.crt.realtors.org:80 FAILED
Firewall Test: demo.crt.realtors.org:6103 FAILED
Firewall Test: retsgw.flexmls.com:80 GOOD
Firewall Test: retsgw.flexmls.com:6103 GOOD
Firewall Result: At least one port 6103 test passed. Likely cause: One of the test servers might be down but connections on port 80 and port 6103 should work.

....For the mls integration to go through this test as to pass before mls data mapping can be done.

**Comment by troydavisson** [comment]
As it states:

> One of the test servers might be down

That server isn't available anymore to test against.

Are you actually having a problem other than what's returned there?  Why do you require that test to pass?

**Comment by premiumBH** [comment]
Also as mentioned earlier the acquired MLS Client solution comes pre-installed with an MLS Addon which supports RETS version 1.72 (vendor discontinued support & development for product after that version). Now...for us to connect any site to our MLS solution (which also we own) we have to use this MLS Addon - But this MLS addon is failing...so we can't get our MLS client solution integrating with our MLS ....

Hope its clear now....

**Comment by troydavisson** [comment]
Do you have the ability to modify the source code for what that's doing, or is a code update to PHRETS the only available option (assuming this client tool you're referring to would pull updates from Github)?

**Comment by premiumBH** [comment]
Yes we do (though that would be a violation of GL on a few levels - but thats least of our concern at this point) however we as yet dont have the expertise on board who specializes in RETS. So I'll have to either have some help on this OR ask my php developer to look into this. 
Assuming we're able to modify....whats the suggested solution?

**Comment by premiumBH** [comment]
Hi Troy, While I've been still waiting to hear back from you to the last post, here's some update: 

Today I asked my developer to fiddle with the API codes and bypass the failing test (demo.crt.realtor.org) after which the error didn't appear however following message appeared: 

http://my.mls:80/rets.php?Command=Login MemberName=BPO GetObject=https://my.mls/rets.php?Command=getobject Login=https://my.mls/rets.php?Command=login Logout=https://my.mls/rets.php?Command=logout Search=https://my.mls/rets.php?Command=search GetMetadata=https://my.mls/rets.php?Command=getmetadata 200

Now I dont know what what exactly means, but all we know was that had the test been successful then the red TEST link should have changed to green TESTED. Which didnt happened, and needless to say we can't begin the mls mapping because there is no mls configured. Can you tell me whats the resolution to this please? 

Thank you in advance

**Comment by troydavisson** [comment]
What you pasted above looks like a response from the RETS server based on a good login, but the response isn't being read or handled correctly.  After PHRETS gets that response from the server, it should have a valid session and follow up requests to the RETS server should work.

If you use a tool such as www.retsmd.com, that should help validate whether or not the RETS server is responding as it should.  Once the RETS server is eliminated as an issue, we'd know that the problem you're having is specifically with the client side and we could probably dig deeper into solving that.

**Comment by premiumBH** [comment]
Troy

Thank you for your kind response. Attached is the error notification from retsmd.com
![screenshot_20170106-001827](https://cloud.githubusercontent.com/assets/24904639/21697994/128544bc-d3a6-11e6-841c-878432284005.png)

**Comment by premiumBH** [comment]
Did another test this time as https://my.mls:80

Got the following message: RETSRequest called but Action passed has no vale. Failed Login
