### ISSUE TITLE
Photo URL retrieval issue

### ISSUE THREAD

**Issue by Aeyzaz** [troydavisson/PHRETS#55]
Hello, I am having a problem in downloading Photos URL, I looked up for the available fields in retsmd.com but didn't find 'Photo Location' Field. but when i try to download the data from RETS Connector it shows me the exact field having all the photo URLs. Moreover, I tried to download the photos using GetObject Method but i dont see Location field there too. 

P.S i am connecting to SANDICOR, Inc. in San Diego.

**Comment by troydavisson** [comment]
This sounds more appropriate for the [mailing list](https://groups.google.com/forum/#!forum/phrets), but to answer your question:

Photo URLs are typically only available through GetObject unless the RETS server has a "Media" resource where you can query records to get that information back.  In RETS Connector's case, it's likely configured to retrieve those URLs from the RETS server (using GetObject).

You'll likely want to note the [5th parameter of GetObject](https://github.com/troydavisson/PHRETS/wiki/GetObject) which defaults to NOT asking for photo URLs.  With that set to "1", the Location attribute/header should come back for those photos.

**Note for others that may stumble on this**: Not all RETS servers support the ability to retrieve photos by URL.  If this method doesn't work for you, it's likely that the RETS server doesn't have a way to get the URLs (in which case there isn't anything PHRETS can change for you).

**Comment by ph3l1x** [comment]
the location field is protected. And your examples seem to be outdated. As they are objects you can not just try to retrieve using $photo['location'] and trying $photo->location does not work since its a protected value. How can I go about getting the location for the photos? I Can see it if i just print_r the $photo object... But how to access it??

**Comment by ashishsinghjmd** [comment]
Hello troy,
As you said for 5th parameter to 1 i use like this ,here is code but i am unable to get image url what is issue... 

foreach ($results as $record) {
   
    $photos = $rets->GetObject("Property", "Photo", $record['MST_MLS_NUMBER'], "*", 1); 
	if ($photos !== null) { 
	 foreach ($photos as $photo) {
			echo 'Location: ', $photo->getLocation(), '<br>';
	 }
	}
}  

This code return 
Location: 0
Location: 0
Location: 0
Location: 0
Location: 0
Location: 0
Location: 0

**Comment by troydavisson** [comment]
RETS servers aren't required to support the `Location` feature, so even though you've asked for it, they aren't required to provide it.  That appears to be what you're running into here.

**Comment by ashishsinghjmd** [comment]
Thanks for your quick reply , 

is there any method to get property image url as i am able to download photo but we need image url as i have  to create xml for xpressdocs and they require image url in xml feed  <PictureUrl></PictureUrl>

Thanks 
Ashish

**Comment by troydavisson** [comment]
You'd need to download the photo, store it somewhere (either locally or in the cloud, like Amazon S3) and then reference a URL to the publicly accessible object from there.  The RETS server doesn't provide you with the URL because they don't want you pointing the additional traffic to their system, so you'll need to run that traffic yourself.

**Comment by ashishsinghjmd** [comment]
Thanks
