### ISSUE TITLE
getLocation always return empty

### ISSUE THREAD

**Issue by davyzhen** [troydavisson/PHRETS#82]
Here is sample code i use:

$objects = $rets->GetObject('Property', 'Photo', 'N3282878', '*', 1);
var_dump($objects);

**Comment by troydavisson** [comment]
Do you get the objects themselves back with the 5th parameter is a `0`?  Not all RETS servers support the ability to give you URLs instead of the direct image, so that's likely what you're seeing here.

If you're still having issues getting even the direct photo, please post to our mailing list (https://groups.google.com/forum/#!forum/phrets) and I'm sure someone can help point you in the right direction.
