### ISSUE TITLE
GetMetadataTable() called but unable to find GetMetadata location. Failed login?

### ISSUE THREAD

**Issue by cncwebdev** [troydavisson/PHRETS#88]
I'm getting an error in phrets_v2 2.php in a website I'm troubleshooting for a client.  The site was developed by a person that no longer works at our company; so, I'm not 100% sure how 'normal' we have things set up.  That said, phrets is being used as part of a WordPress plugin called idx-updater to update IDX Broker records on our client's site from http://nom.mlsmatrix.com.  

My client's original complaint was that there was a specific listing that she could not upload.  When I tried running idx-updater to manually pull it, I get the error: 

"Warning: touch() [function.touch]: Unable to create file because No such file or directory in /home/content/95/6302395/html/clients/ricewp/wp-content/plugins/rice-idx-updater/phrets/lib/phrets_v2.php on line 1391
GetMetadataTable() called but unable to find GetMetadata location. Failed login?"   

This webapp has been working for the client flawlessly for the past 6 months and she has not recently changed any login credentials as far as I can tell.  Any ideas about what would cause this and/or ways to make it work?

**Comment by troydavisson** [comment]
I'd recommend using your credentials to log into www.retsmd.com.  My guess is that the RETS server is not advertising that it supports the GetMetadata transaction which is why PHRETS is failing to make that request for you.  This is required in order for PHRETS to know how to make that request to get you what you're asking.  Towards the very top of the retsmd.com page after you login, the Transactions list should appear.  Make sure GetMetadata appears there.  If it doesn't, you'll need to get in contact with the person that provided you with the credentials to see if you can be granted access to see the metadata.

**Comment by vinayakac** [comment]
Hello,
I am also facing same issue with PHRETS.
GetMetadataTable() called but unable to find GetMetadata location. Failed login?

Please give suggestion on this.

**Comment by ezinaz** [comment]
Interesting.  I appear to have the same issue.  The "capabilities" array in the response only has a value for "Login".  My login works on retsmd so there does not appear to be a login issue.

  ["capabilities":protected]=>
  object(PHRETS\Capabilities)#21 (1) {
    ["capabilities":protected]=>
    array(1) {
      ["Login"]=>
      string(39) "http://retsgw.flexmls.com/rets2_3/Login"
    }
  }

**Comment by ezinaz** [comment]
Resulting error is:

[ec2-user@ip-xxx-xx-xx-xxxx scripts]$ php mls-login.php > ez17.log
PHP Fatal error:  Uncaught exception 'PHRETS\Exceptions\CapabilityUnavailable' with message ''GetMetadata' tried but no valid endpoint was found.  Did you forget to Login()?' in /home/ec2-user/scripts/vendor/troydavisson/phrets/src/Session.php:335
Stack trace:
#0 /home/ec2-user/scripts/vendor/troydavisson/phrets/src/Session.php(256): PHRETS\Session->request('GetMetadata', Array)
#1 /home/ec2-user/scripts/vendor/troydavisson/phrets/src/Session.php(169): PHRETS\Session->MakeMetadataRequest('METADATA-SYSTEM', 0, 'metadata.system')
#2 /home/ec2-user/scripts/mls-login.php(23): PHRETS\Session->GetSystemMetadata()
#3 {main}
  thrown in /home/ec2-user/scripts/vendor/troydavisson/phrets/src/Session.php on line 335
[ec2-user@ip-172-31-13-105 scripts]$

**Comment by ezinaz** [comment]
Code looks like this:

<?php 

date_default_timezone_set('America/Phoenix');

require_once("vendor/autoload.php");

$log = new \Monolog\Logger('PHRETS');
$log->pushHandler(new \Monolog\Handler\StreamHandler('app.log', \Monolog\Logger::DEBUG));


$config = new \PHRETS\Configuration;
$config->setLoginUrl('http://retsgw.flexmls.com/rets2_3/Login')
	->setUsername('HIDDEN')
	->setPassword('HIDDEN')
	->setRetsVersion('1.5');

$rets = new \PHRETS\Session($config);
$rets->setLogger($log);

$connect = $rets->Login();
var_dump($connect);

$system = $rets->GetSystemMetadata();
var_dump($system);

echo "Server Name: " . $system->getSystemDescription();

?>

**Comment by theodorebear** [comment]
@ezinaz @troydavisson 
I am having the same issue. I can connect to RETS server via login but I get back a capabilities array that only includes Login. Logging in to RetsMD works fine so it is not a credentials issue. 
I then encounter an error "Uncaught exception 'PHRETS\Exceptions\CapabilityUnavailable' with message ''GetMetadata' tried but no valid endpoint was found" whenever I try to GetMetadata.
I think maybe because upon logging in the data returned does not include a GetMetadata URL whereas with other RETS servers it specifies it in the login response.
How can I fix this?
